name: Deploy CloudFormation Stack

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change to your region

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation create-stack \
            --stack-name donor-sys-stack \
            --template-body file://stack/donor-sys-stack.yml \
            --parameters ParameterKey=KeyName,ParameterValue=donor_key

            echo "Waiting for stack creation to complete..."

          aws cloudformation wait stack-create-complete \
            --stack-name donor-sys-stack

      - name: Get Stack Outputs
        run: |
          echo "Stack Outputs:"
          aws cloudformation describe-stacks \
            --stack-name donor-sys-stack \
            --query "Stacks[0].Outputs"

      - name: Get Stack Status
        run: |
          echo "Stack Status:"
          aws cloudformation describe-stacks \
            --stack-name donor-sys-stack \
            --query "Stacks[0].StackStatus"

